### ISSUE TITLE
Used color seems to be darker than the chosen one when changing hierarchy to custom color

### ISSUE THREAD

**Issue by azfoo** [FelipeDefensor/TiLiA#107]

**Comment by azfoo** [comment]
Pretty sure the used color is not darker than the chosen color, but the index for colors starts at 0 whereas the index for levels starts at 1, so the 0th color is never used. Would you like me to fix that?

**Comment by FelipeDefensor** [comment]
Did you check the colors when setting them using Right click > change color? That's when the difference occurs. The previous title did not make that clear.

As an example, if we choose this color which looks like pure white:

![Uploading choice.png…]()

We get a hierarchy that's clearly gray (even when deselected).

![result](https://github.com/FelipeDefensor/TiLiA/assets/87732202/3b6d880c-0fda-46c1-b155-95059da6c134)

**Comment by FelipeDefensor** [comment]
About the color indexing, yes, let's fix that. 

Also, I think we should go with some orange for the first level to match the logo. I suggest something like #ff964f to match the current pastel palette. The green that's in the currently unused first level could come after that.
