### ISSUE TITLE
Windows Defender blocks installation

### ISSUE THREAD

**Issue by FelipeDefensor** [FelipeDefensor/TiLiA#38]

**Comment by FelipeDefensor** [comment]
Windows 10, computador do Gabech

**Comment by FelipeDefensor** [comment]
Avast antivirus required scan before executing installer.

**Comment by lgabech** [comment]
Possible solution at
https://stackoverflow.com/questions/48946680/how-to-avoid-the-windows-defender-smartscreen-prevented-an-unrecognized-app-fro

**Comment by expectopatronum** [comment]
Hi, 
I am one of your reviewers over at https://github.com/openjournals/joss-reviews/issues/8417 👋 

When I tried to install the desktop application on my Windows PC, I noticed that this issue still persists: 
<img width="530" height="509" alt="Image" src="https://github.com/user-attachments/assets/57369c01-e0b7-4e80-a44d-6d062b5c70bf" />

Did you try any of [the options](https://stackoverflow.com/a/66582477/1117932) for gaining reputation?

Best regards
Verena

**Comment by FelipeDefensor** [comment]
Worth noting that this is mentioned in that installation instructions: https://tilia-app.com/help/installation/
