### ISSUE TITLE
Is ffmpeg necessary for playing back local files?

### ISSUE THREAD

**Issue by FelipeDefensor** [FelipeDefensor/TiLiA#98]
Opening this to continue discussion we've been having by e-mail. Does `ffmpeg` need to be installed for TiLiA to playback local files?

**Comment by FelipeDefensor** [comment]
@azfoo Let's continue talking here. 

You mentioned that you are unable to load any audio on a clean install of TiLiA. I think I have reproduced that behavior with `ffmpeg` installed. Following a hunch about what's going on, I was able to fix it by running TiLiA with admin privileges. Does that fix it on your end?

It would be very weird that `ffmpeg` is both required for playback and not bundled with `PyQt` because I have succesfully loaded media in previous versions of TiLiA in several different computers and some of them definitely didn't have `ffmpeg` available.

**Comment by azfoo** [comment]
So I tested things again and it seems that PyQt6.6 doesn't have the issue, but 6.7 has. Perhaps downgrading and defining PyQt's version would be a quick fix?

**Comment by FelipeDefensor** [comment]
Will try, but I'm away from my setup until Monday.

**Comment by FelipeDefensor** [comment]
> Try: `pip install --force-reinstall PyQt6==6.6.0 PyQt6-Qt6==6.6.0 PyQt6-sip==13.6.0 PyQt6-WebEngine==6.6.0 PyQt6-WebEngine-Qt6==6.6.0`?

Installing all dependencies with `pip install -e .` and then downgrading PyQt with the above works on a fresh environment on Windows 11. I will retry this on my usual setup tomorrow, but I think we can be confident that this works.

**Comment by FelipeDefensor** [comment]
> > Try: `pip install --force-reinstall PyQt6==6.6.0 PyQt6-Qt6==6.6.0 PyQt6-sip==13.6.0 PyQt6-WebEngine==6.6.0 PyQt6-WebEngine-Qt6==6.6.0`?
> 
> Installing all dependencies with `pip install -e .` and then downgrading PyQt with the above works on a fresh environment on Windows 11. I will retry this on my usual setup tomorrow, but I think we can be confident that this works.

Confirming that this also works on my usual setup.

**Comment by FelipeDefensor** [comment]
I'm closing this one as this douments the `PyQt` version issue. The question about bundling ffmpeg separately remains, though.

**Comment by FelipeDefensor** [comment]
I'm closing this one as this douments the PyQt version issue. The question about bundling ffmpeg separately remains, though.
